### PR TITLE
Pass Urban Airship extras as dictionary instead of string; Fix typo in method name

### PR DESCRIPTION
**Pull request by doublerebel**
Brings Android module up to parity with `.data` property from iOS notifications:

http://docs.appcelerator.com/titanium/latest/#!/api/PushNotificationData

### CODE REVIEW

**Comment by muhammaddadu** [comment]
Hey @ygbr, have you signed the [CLA](http://cla.appcelerator.com)?

**Comment by doublerebel** [comment]
@muhammaddadu Do you need an updated version of this module?  I need one this week myself.

**Comment by muhammaddadu** [comment]
@doublerebel This repository has been depreciated. We are trying to move PRs to the new repository found [here](https://github.com/appcelerator-modules/ti.urbanairship).

**Comment by muhammaddadu** [comment]
Hey @doublerebel, have you signed the [CLA](https://cla.appcelerator.com)?

**Comment by doublerebel** [comment]
@muhammaddadu Ahh, I see now in the README.  Thanks, just signed it!  Should I clean up this PR and apply it to the new repo?

**Comment by muhammaddadu** [comment]
Thanks @doublerebel. It would be great if you could.

**Pull request closed without merging**
